# extends https://yamllint.readthedocs.io/en/stable/configuration.html#default-configuration
extends: default

#yaml-files:
#  - 'dir/*.conf'
#  - 'dir/dir/*.conf'

rules:
  document-start: disable
  truthy:
    check-keys: false
  line-length:
    max: 120
